// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQVIUKAaKyBbBPb-Jm8P74_F1VSPqvaU',
    appId: '1:650903981970:web:2833b1dc5645b93194bb4b',
    messagingSenderId: '650903981970',
    projectId: 'auth-development-2630a',
    authDomain: 'auth-development-2630a.firebaseapp.com',
    storageBucket: 'auth-development-2630a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9UQsYtuE9Xi_krrLZwBP0KuINpHyAi1k',
    appId: '1:499462805344:android:806adf0c1eee507411f005',
    messagingSenderId: '499462805344',
    projectId: 'flutter-chat-app-ab853',
    storageBucket: 'flutter-chat-app-ab853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBST5oYnLLnKlBP1GhuEfedU5GVtimxE',
    appId: '1:499462805344:ios:fbdf8411bd09c53a11f005',
    messagingSenderId: '499462805344',
    projectId: 'flutter-chat-app-ab853',
    storageBucket: 'flutter-chat-app-ab853.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp08kVr3Uwnaww3kRqnd3C2-a7qj3D9ak',
    appId: '1:650903981970:ios:d5527d8ee38b605194bb4b',
    messagingSenderId: '650903981970',
    projectId: 'auth-development-2630a',
    storageBucket: 'auth-development-2630a.firebasestorage.app',
    iosClientId: '650903981970-m769ldjao7hc23itqpcaib6t9vpmm594.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNXLeicZAWKYkc3jfz-jOqdd195Im35g',
    appId: '1:650903981970:web:6ba22d1a0733589994bb4b',
    messagingSenderId: '650903981970',
    projectId: 'auth-development-2630a',
    authDomain: 'auth-development-2630a.firebaseapp.com',
    storageBucket: 'auth-development-2630a.firebasestorage.app',
  );
}